# Generated by Django 2.2.4 on 2019-08-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['created'], 'permissions': [('api_access', 'Can access the API'), ('extended_expiry', 'Can set an expiry time of up to two weeks'), ('no_expiry', 'Can set an infinite expiry time, or none at all')]},
        ),
    ]
