# Generated by Django 2.2.4 on 2019-08-23 03:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190821_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Extraneous data.'),
        ),
    ]
