# Generated by Django 2.2.4 on 2019-09-16 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_page_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
