# Generated by Django 2.2.4 on 2019-10-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='guild',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='privacy',
            field=models.CharField(default='public', max_length=10),
        ),
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(help_text='Log type.', max_length=40, null=True),
        ),
    ]
