# Generated by Django 2.2.4 on 2019-10-26 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20191009_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(help_text='Whitelisted log type.', max_length=40)),
                ('users', models.ManyToManyField(help_text='User whitelists.', related_name='whitelists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
