# Generated by Django 2.2.8 on 2020-01-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_whitelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='guild',
            field=models.BigIntegerField(null=True),
        ),
    ]
