# Generated by Django 3.1 on 2020-08-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200111_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='data',
            field=models.JSONField(default=dict, help_text='Extraneous data.'),
        ),
        migrations.AlterField(
            model_name='log',
            name='users',
            field=models.JSONField(default=list, help_text='List of users in log.'),
        ),
        migrations.AlterField(
            model_name='page',
            name='messages',
            field=models.JSONField(editable=False, help_text="Page's messages."),
        ),
    ]
