# Generated by Django 3.1 on 2020-11-30 21:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_auto_20200827_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelist',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='User whitelists.', related_name='whitelists', to=settings.AUTH_USER_MODEL),
        ),
    ]
